apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configmap.name}}
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ end }}
data:
  index.html: | 
    {{ .Values.configmap.html | nindent 4 }}