apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ikapanadze-binding
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ end }}
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceaccount.name}}
    namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ end }}
roleRef:
  kind: Role
  name: {{.Values.role.name}}
  apiGroup: rbac.authorization.k8s.io
