apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name}}
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ end }}
spec:
  gateways:
    - {{.Values.virtualservice.gateway}}
  hosts:
    - {{.Values.virtualservice.host}}
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{.Values.service.name}}
        port: 
          number: {{.Values.service.port}}
